## 日志配置
logging:
  pattern:
    # 日志输出格式 (默认: %d{yyyy-MM-dd HH:mm:ss.SSS} %p %c{1} [%t] %m%n)
    #%m   输出代码中指定的消息
    #%p   输出优先级，即DEBUG，INFO，WARN，ERROR，FATAL
    #%r   输出自应用启动到输出该log信息耗费的毫秒数
    #%c   输出所属的类目，通常就是所在类的全名  %c{1}表示缩写包名只显示类名
    #%t   输出产生该日志事件的线程名
    #%n   输出一个回车换行符，Windows平台为“\\r\\n”，Unix平台为“\\n”
    #%d   输出日志时间点的日期或时间,默认格式为ISO8601,也可以在其后指定格式，比如%d{yyy MMM dd HH:mm:ss,SSS}，输出类似：2018年6月15日22:10:28，921
    #%l   输出日志事件的发生位置，包括类目名、发生的线程，以及在代码中的行数。举例：estlog4.main(TestLog4.java: 10)
    console: "%d{yyyy-MM-dd HH:mm:ss} -%p -%c{1} -%m 耗时%r 毫秒 %n"
  file:
    # 日志文件路径可用相对路径与绝对路径，直接指定文件名则保存到项目路径下
    name: ../log/ledger.log
  level:
    # 打印SQL日志
    com.com.questionnaire.db.mapper: debug