# 数据库 配置
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ledger?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

db:
  url: "jdbc:mysql://mysql:3306/ledger?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false"
  username: root
  password: root

# mybatis-plus 配置
mybatis-plus:
  # 配置需要别名的类的包路径，自动给该包下的类配置别名 默认为类名
  type-aliases-package: com.ledger.db.entity
  # 配置xml映射文件路径 多个时使用逗号分隔
  mapper-locations: classpath:/mapper/*.xml, classpath:/mapper/*/*.xml
  # Mybatis的执行器类型 batch 批量操作
  executor-type: reuse
  # 全局配置
  global-config:
    # 不再打印 Mybatis-Plus的LOGO
    banner: false
    db-config:
      # 全局逻辑删除的实体字段名(since 3.3.0版本后可以忽略不配置步骤2（通过给字段加上注解 @TableLogic来实现）)
      #logic-delete-field: flag
      # 逻辑未删除值(默认为 0)
      #logic-not-delete-value: 0
      # 逻辑已删除值(默认为 1)
      #logic-delete-value: 1
      # 对插入的参数进行校验
      insert-strategy: not_empty
      # 对修改的参数进行校验
      update-strategy: not_empty
      # 对查询的where条件参数进行校验
      where-strategy: not_empty
  # 配置
  configuration:
    # 自动映射时 遇到未知列or未知属性处理策略 warning 打印日志警告 failing 当作映射失败处理，并抛出异常
    auto-mapping-unknown-column-behavior: warning
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    # 开启二级缓存
    cache-enabled: true
    # 一级缓存, 同一个Session会话执行相同查询语句不会再次查询数据库
    # 单服务架构中（有且仅有只有一个程序提供相同服务），一级缓存开启不会影响业务，只会提高性能, 微服务则需要关闭一级缓存
    local-cache-scope: session
    # 日志实现
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 语句超时
    default-statement-timeout: 2500